### PR TITLE
Test that mysql remarks

### PR DESCRIPTION
**Pull request by nvoxland**
## Description

Test for liquibase/liquibase#2301 where adding remarks to a primary key column removes the primary key definition.

### CODE REVIEW

**Comment by KushnirykOleh** [comment]
Should this PR be merged to main or to develop branch?

**Comment by kristyldatical** [comment]
> Should this PR be merged to main or to develop branch?

@nvoxland -- the fact that the new MySQL test you added is failing against `main` with ```Failed tests:   apply createTableWithRemarks against mysql 5.7(liquibase.harness.change.ChangeObjectTests): Condition failed with Exception:(..)``` indicates I think that we should run this against `develop` and a matched Liquibase branch snapshot with the fix in it?

**Review by kristyldatical — CHANGES_REQUESTED** [review]
@nvoxland -- please change to PR to be against `develop` and not `main`.

**Comment by nvoxland** [comment]
Yep, sorry. All my PRs should go to `develop` but I'm still getting used to having to pay attention to the branch on a new PR...

**Comment by nvoxland** [comment]
Right @kristyldatical . All these PRs for fixes in liquibase should go to 'develop', and whenever liquibase releases we'll merge develop to main.

**Pull request merged**
