### PR TITLE
LB PR-1908: Handle autoincrement GENERATED BY DEFAULT IDENTITY COLUMNS for newer CRDB versions.

### PR DESCRIPTION
**Pull request by XDelphiGrl**
These test cases are added to validate [liquibase/liquibase PR 1908](https://github.com/liquibase/liquibase/pull/1908) . 

#### CRDB Versions Less than 21.2
* Generated SQL for autoincrmement SQL statements use SMALLSERIAL, SERIAL and BIGSERIAL. For example,

```
CREATE TABLE public.pr1908 (id_smallint SMALLSERIAL, id_int SERIAL, id_integer SERIAL, id_int8 BIGSERIAL, id_int64 INT64, id_bigint BIGSERIAL);
```

#### CRDB Versions Greater than or Equal to 21.2
* Generated SQL for autoincrement SQL statements use GENERATED BY DEFAULT AS IDENTITY. For example,

```
CREATE TABLE public.pr1908 (id_smallint SMALLINT GENERATED BY DEFAULT AS IDENTITY, id_int INTEGER GENERATED BY DEFAULT AS IDENTITY, id_integer INTEGER GENERATED BY DEFAULT AS IDENTITY, id_int8 BIGINT GENERATED BY DEFAULT AS IDENTITY, id_int64 INT64 GENERATED BY DEFAULT AS IDENTITY, id_bigint BIGINT GENERATED BY DEFAULT AS IDENTITY);-->
```

### CODE REVIEW

**Review by KushnirykOleh — APPROVED** [review]

**Comment by KushnirykOleh** [comment]
Hey, @XDelphiGrl for version 21.2 cockroachDB also generate sequences for autoincrement columns that aren't deleted during auto rollback. Because of that other testcase fails as it doesn't expect that sequences to be present in DB.
How this should be handled?
IF that's expected behaviour and liquibase can't\shouldn't do anything about that we add 
6 dropSequence chnageObejcts for
pr1908_id_smallint_seq
pr1908_id_integer_seq
pr1908_id_int_seq
pr1908_id_int8_seq
pr1908_id_int64_seq
pr1908_id_bigint_seq
together with dropTable in rollback section for >=21.1

**Comment by KushnirykOleh** [comment]
Also would be nice to merge this PR after https://github.com/liquibase/liquibase-test-harness/pull/204

**Comment by XDelphiGrl** [comment]
@KushnirykOleh, I will take a look at this test again. I was not aware of the sequences; I am not immediately clear on if this is intended Liquibase behavior or not. Thank you for bringing it to my attention!

**Comment by XDelphiGrl** [comment]
This has been open for a year and I haven't gotten back to addressing the PR comments. Closing.

**Pull request closed without merging**
