### PR TITLE
merging develop into main after 4.19 release

### PR DESCRIPTION
**Pull request by KushnirykOleh**

### CODE REVIEW

**Review by vitaliimak — APPROVED** [review]

**Comment by KushnirykOleh** [comment]
createTableDataTypeDoubleIsFloat test failed when running on develop branch
https://github.com/liquibase/liquibase-test-harness/actions/runs/4255003780/jobs/7402041712#step:7:15647

**Comment by KushnirykOleh** [comment]
@filipelautert @XDelphiGrl when generating snapshot "typeName" for this column is "DOUBLE"
image
Is it expected?

**Comment by filipelautert** [comment]
@KushnirykOleh for 4.19.1 we merged this PR https://github.com/liquibase/liquibase/pull/3703 that improves DOUBLE type handling for snowflake -> Double is an alias for the FLOAT data type in Snowflake.

**Comment by KushnirykOleh** [comment]
Yes, i got that this change was to remove precision where it doesn't need to be.
The issue with this [PR](https://github.com/liquibase/liquibase-test-harness/pull/481) is that test fails because expected json contains `"typeName": "FLOAT"` for `FLOATCOL` column, but actual typeName is `DOUBLE` is generated snapshot.

**Comment by KushnirykOleh** [comment]
created https://github.com/liquibase/liquibase-test-harness/pull/529 to fix test to merge develop into main

**Pull request merged**
