### PR TITLE
[DAT-10789] Added AWS MariaDb support

### PR DESCRIPTION
**Pull request by yodzhubeiskyi**

### CODE REVIEW

**Comment by kristyldatical** [comment]
@jnewton03 -- could you please review this PR and approve if it can be merged.

**Comment by jnewton03** [comment]
Hi @kristyldatical , we will need to get https://github.com/Datical/liquibase-infrastructure/pull/558 merged in first to create the static infrastructure.  I believe the last remaining item from @ap-liquibase was to get the database URL stored as a GHA Secret.  If that wasn't working then we'd need to edit the harness-config.yml to include the URL for now.  @ap-liquibase please advise.

**Comment by ap-liquibase** [comment]
Hi @jnewton03 @kristyldatical dotting the i's and crossing t's on https://github.com/Datical/liquibase-infrastructure/pull/558 now. Should be done here shortly

**Comment by ap-liquibase** [comment]
@kristyldatical @jnewton03 The static infrastructure for test harness (and pro-tests) have been created.

**Review by jnewton03 — APPROVED** [review]

**Review by KushnirykOleh — APPROVED** [review]

**Pull request merged**
