### PR TITLE
Mysql and friends do not support incrementBy on addAutoIncrement

### PR DESCRIPTION
**Pull request by nvoxland**
## Description

Test updates for liquibase/liquibase#3026

### CODE REVIEW

**Review by XDelphiGrl — COMMENTED** [review]
Hi, @nvoxland - Did you not also need to add any of the associated validation files for these tests?

**Comment by nvoxland** [comment]
No, @XDelphiGrl, there were validation files already there which continue to work. For mysql/mariadb, we used to ignore the incrementBy field so there was nothing about it in the validation. Now I took those fields off on these database-specific overrides of default addAutoIncrement changelogs and the SQL for those remain the same.

**Comment by XDelphiGrl** [comment]
Thank you for the explanation about the validation files, @nvoxland .

**Comment by nvoxland** [comment]
Since the core PR got merged, I have to merge this to develop to keep tests passing. If you have comments, I can make an additional PR with changes

**Pull request merged**
