### PR TITLE
DAT-14267: add liquibase-github-action to update mssql database

### PR DESCRIPTION
**Pull request by jandroav**
feat(mssql.sql): add liquibase changeset to add lbuser and grant db_owner role to it
[DAT-14267](https://datical.atlassian.net/browse/DAT-14267)

[DAT-14267]: https://datical.atlassian.net/browse/DAT-14267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jandroav** [comment]
I am getting:

```
Unexpected error running Liquibase: Cannot invoke "Object.getClass()" because "unexpectedObject" is null
```
here: https://github.com/liquibase/liquibase-test-harness/actions/runs/4666624792/jobs/8261428473

It is failing in the `drop-all` step, before the new code. Any idea about what is happening? @yodzhubeiskyi  Could you please take a look when you have time?

**Comment by jandroav** [comment]
> 

Changed and run a build with `logLevel: INFO`. It seems liquibase can perform the drop but it fails at the end: https://github.com/liquibase/liquibase-test-harness/actions/runs/4675293365/jobs/8280278955

**Comment by jnewton03** [comment]
@jandroav would a cleaner solution be to check if the user already exists first?  Something like:

```
USE lbcat;

IF NOT EXISTS (SELECT * FROM sys.sysusers WHERE name = 'lbuser')
BEGIN
    EXEC sp_adduser 'lbuser';
END

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'lbuser' AND type_desc = 'DATABASE_ROLE' AND is_fixed_role = 0)
BEGIN
    EXEC sp_addrolemember 'db_owner', 'lbuser';
END
```

**Comment by KushnirykOleh** [comment]
@jandroav , after Pavlo's [PR](https://github.com/liquibase/liquibase-test-harness/pull/539) mssql on gcp seems to be working fine, i not sure if we need recreating user for test-harness tests

**Comment by jandroav** [comment]
> 

It seems not necessary and I can see it is working fine now. thanks!

**Comment by jnewton03** [comment]
so should this pr be closed and ticket moved to done?

**Comment by jandroav** [comment]
> 

After fixing branch conflicts we need to merge our already tested change:

```
USE lbcat;

IF NOT EXISTS (SELECT * FROM sys.sysusers WHERE name = 'lbuser')
BEGIN
    EXEC sp_adduser 'lbuser';
END

IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = 'lbuser' AND type_desc = 'DATABASE_ROLE' AND is_fixed_role = 0)
BEGIN
    EXEC sp_addrolemember 'db_owner', 'lbuser';
END
```

@PavloTytarchuk I could see GCP `mssql` tests are failing again with the same issue https://github.com/liquibase/liquibase-test-harness/actions/runs/4816521824/jobs/8576252537

**Comment by KushnirykOleh** [comment]
@jandroav looking at this issue with @PavloTytarchuk we discovered most likely that dropAll doesn't work because of different schemas `dbo` (used in init script) and `lbuser` used in tests. 
So recreating user won't resolve the issue.
We will try to figure out correct approach for gcp mssql as such config seems to be working differently that on AWS

**Review by PavloTytarchuk — APPROVED** [review]

**Pull request merged**
