### PR TITLE
Test loadData in mariadb with BLOBs

### PR DESCRIPTION
**Pull request by nvoxland**
Test for https://github.com/liquibase/liquibase/pull/2595

### CODE REVIEW

**Comment by MichaelCkr** [comment]
In my scenario, resulting in https://github.com/liquibase/liquibase/pull/2595, I had a CLOB set instead of a BLOB, in the relevant column in the loadData changeset and my database column is configured as a "varchar2(2048)" (which confuses me a little bit by now).
But I think the test looks correct (also regarding the failure in the test execution) for the fix from https://github.com/liquibase/liquibase/pull/2595.

If you like, I can add your testcase in my pull request to check the test executions.

Thank you very much for adding the test.

**Comment by nvoxland** [comment]
The tests are failing because it's grabbing liquibase master, not the build from the fork. I'll look into how to fix that up.

**Comment by MichaelCkr** [comment]
It was clear to me, that your PR tests against master, but I haven't recognized, that it's in a separate repository. :)

**Review by XDelphiGrl — CHANGES_REQUESTED** [review]
@nvoxland , in https://github.com/liquibase/liquibase/pull/2595, you mention that the change impacts both MySQL and MariaDB. The tests added are for MariaDB only. Can you either "generalize" this test or add MySQL specific test files?

**Review by XDelphiGrl — APPROVED** [review]
Tests for BLOBs for MariaDB and MySQL look good. It is noted in the XML test files that you must have `needsPreparedStatement=true` in order to use BLOBS. Calling that out here, too, for those who may not read the XML files. Although, who wouldn't?! XML files are scintillating!

APPROVED

**Pull request merged**
